config/routes.rb
Tunecore::Application.routes.draw do
  resources :songs
  resources :albums
  resources :artists
  get '/search', to: 'music_searches#index'
  root to: 'home#show'
end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :artist_id, :title, :year
  validates_presence_of :artist_id, :title, :year
  belongs_to :artist
  has_many :songs
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :name
  validates_presence_of :name
  has_many :albums
end

app/models/music_search.rb
class MusicSearch < ActiveRecord::Base
  extend Textacular

  attr_writer :query
  attr_accessible :query
  belongs_to :result, polymorphic: true

  def self.search(query)
    Rails.cache.fetch([cache_key, query]) do
      super.preload(:result).map(&:result)
    end
  end

  def self.cache_key
    ['MusicSearch', Album.maximum(:updated_at).to_i, Artist.maximum(:updated_at).to_i, Song.maximum(:updated_at).to_i].join('/')
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :album_id, :title
  validates_presence_of :title, :album_id
  belongs_to :album
  has_one :artist, :through => :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist = Artist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/new
  # GET /artists/new.json
  def new
    @artist = Artist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/1/edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(params[:artist])

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render json: @artist, status: :created, location: @artist }
      else
        format.html { render action: "new" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /artists/1
  # PUT /artists/1.json
  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/music_searches_controller.rb
class MusicSearchesController < ApplicationController
  before_filter :require_search_term

  def index
    @results = MusicSearch.search(params[:q]).map { |r| MusicSearchResultPresenter.new(r) }
  end

  private def require_search_term
    if params[:q].blank?
      flash[:error] = "Please provide a search term"
      redirect_to :back
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/albums/_form.html.haml
= form_for(@album) do |f|
  - if @album.errors.any?
    #error_explanation
      %h2
        = pluralize(@album.errors.count, "error")
        prohibited this album from being saved:
      %ul
        - @album.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br/
    = f.text_area :title
  .field
    = f.label :artist_id
    %br/
    = f.number_field :artist_id
  .field
    = f.label :year
    %br/
    = f.number_field :year
  .actions
    = f.submit

app/views/albums/edit.html.haml
%h1 Editing album
= render 'form'
= link_to 'Show', @album
|
\#{link_to 'Back', albums_path}

app/views/albums/index.html.haml
%h1 Listing albums
%table
  %tr
    %th Title
    %th Artist
    %th Year
    %th
    %th
    %th
  - @albums.each do |album|
    %tr
      %td= album.title
      %td= album.artist.name
      %td= album.year
      %td= link_to 'Show', album
      %td= link_to 'Edit', edit_album_path(album)
      %td= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Album', new_album_path

app/views/albums/new.html.haml
%h1 New album
= render 'form'
= link_to 'Back', albums_path

app/views/albums/show.html.haml
%p#notice= notice
%p
  %b Title:
  = @album.title
%p
  %b Artist:
  = @album.artist.name
%p
  %b Year:
  = @album.year
= link_to 'Edit', edit_album_path(@album)
|
\#{link_to 'Back', albums_path}

app/views/artists/_form.html.haml
= form_for(@artist) do |f|
  - if @artist.errors.any?
    #error_explanation
      %h2
        = pluralize(@artist.errors.count, "error")
        prohibited this artist from being saved:
      %ul
        - @artist.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_area :name
  .actions
    = f.submit

app/views/artists/edit.html.haml
%h1 Editing artist
= render 'form'
= link_to 'Show', @artist
|
\#{link_to 'Back', artists_path}

app/views/artists/index.html.haml
%h1 Listing artists
%table
  %tr
    %th Name
    %th
    %th
    %th
  - @artists.each do |artist|
    %tr
      %td= artist.name
      %td= link_to 'Show', artist
      %td= link_to 'Edit', edit_artist_path(artist)
      %td= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Artist', new_artist_path

app/views/artists/new.html.haml
%h1 New artist
= render 'form'
= link_to 'Back', artists_path

app/views/artists/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @artist.name
= link_to 'Edit', edit_artist_path(@artist)
|
\#{link_to 'Back', artists_path}

app/views/home/show.html.haml
- if flash[:error]
  .error
    %strong= flash[:error]

%h2 Search
%form{ action: '/search', method: 'GET' }
  %input.search{ type: 'search', name: 'q', placeholder: 'Search query (song, artist, album title, or year)' }
  %input{ type: 'submit', value: 'Search' }


%h2 Last 10 Songs
%ul
  - Song.last(10).each do |song|
    %li
      %a{ href: song_path(song) }= SongPresenter.new(song).title_string

%h2 Last 10 Artists
%ul
  - Artist.last(10).each do |artist|
    %li
      %a{ href: artist_path(artist) }= ArtistPresenter.new(artist).title_string

%h2 Last 10 Albums
%ul
  - Album.last(10).each do |album|
    %li
      %a{ href: album_path(album) }= AlbumPresenter.new(album).title_string

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tunecore
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/music_searches/index.html.haml
- if @results.size > 0
  %ul
    - @results.each do |result|
      %li
        %a{ href: url_for(result) }= result.title_string
- else
  %p
    %strong No results for '#{params[:q]}'!

app/views/songs/_form.html.haml
= form_for(@song) do |f|
  - if @song.errors.any?
    #error_explanation
      %h2
        = pluralize(@song.errors.count, "error")
        prohibited this song from being saved:
      %ul
        - @song.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br/
    = f.text_area :title
  .field
    = f.label :album_id
    %br/
    = f.number_field :album_id
  .actions
    = f.submit

app/views/songs/edit.html.haml
%h1 Editing song
= render 'form'
= link_to 'Show', @song
|
\#{link_to 'Back', songs_path}

app/views/songs/index.html.haml
%h1 Listing songs
%table
  %tr
    %th Title
    %th Album
    %th
    %th
    %th
  - @songs.each do |song|
    %tr
      %td= song.title
      %td= song.album_id
      %td= link_to 'Show', song
      %td= link_to 'Edit', edit_song_path(song)
      %td= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Song', new_song_path

app/views/songs/new.html.haml
%h1 New song
= render 'form'
= link_to 'Back', songs_path

app/views/songs/show.html.haml
%p#notice= notice
%p
  %b Title:
  = @song.title
%p
  %b Album:
  = @song.album.title
= link_to 'Edit', edit_song_path(@song)
|
\#{link_to 'Back', songs_path}